### PR TITLE
Support for Laravel 5.8

### PR DESCRIPTION
**Pull request by voicecode-bv**

### CODE REVIEW

**Comment by martinlindhe** [comment]
As a rule of thumb it makes sense to separate different changes into different PR:s.

This PR contains
* Laravel 5.8 support
* Unrelated new feature of disabling output messages (I thought we had this already somewhere, thanks)
* Unrelated cosmetic changes

All looks good tho and I'll merge. But for easy cooperation with random people going forward, please consider limiting your PR:s.

**Comment by voicecode-bv** [comment]
Sorry about that. I noticed it too late. I don't know why the optional output of messages is included again, that was already merged before...

**Comment by martinlindhe** [comment]
I think because you didn't base your work against the git-master branch.

The show output text is in git-master: https://github.com/martinlindhe/laravel-vue-i18n-generator/blob/master/src/config/vue-i18n-generator.php#L79

**Comment by voicecode-bv** [comment]
Yeah I noticed, I was the one who committed that PR back then. Will pay more attention the next time ;-)

**Comment by martinlindhe** [comment]
Ah, that makes sense :-)

**Comment by martinlindhe** [comment]
Resolved with #77

**Pull request closed without merging**
