### PR TITLE
Laravel 7 compatibility

### PR DESCRIPTION
**Pull request by code2prog**
seems to be working properly

### CODE REVIEW

**Comment by Jaspur** [comment]
@martinlindhe can you merge this? thanks @code2prog

**Comment by oliverlundquist** [comment]
@martinlindhe please merge 🙏

**Comment by mpont91** [comment]
We need this! 😢

**Comment by borealsmith** [comment]
@martinlindhe +1 on could you please merge :)

**Comment by code2prog** [comment]
> We need this! 😢

you can make a fork of my repository and use it this way without waiting :)

**Comment by martinlindhe** [comment]
Merged https://github.com/martinlindhe/laravel-vue-i18n-generator/pull/113 (same change)

**Comment by martinlindhe** [comment]
Sorry for being slow on this.

**Pull request closed without merging**
