### PR TITLE
Deterministic multi-file output

### PR DESCRIPTION
**Pull request by murrant**
My own attempt at #109 using scandir() because it is sorted.
Required for #111

### CODE REVIEW

**Comment by murrant** [comment]
@kapalla can you test this?

**Comment by kapalla** [comment]
> @kapalla can you test this?

Sorry for the late response, @murrant . Yes, it's working 👍

**Comment by murrant** [comment]
@martinlindhe anything blocking this?

**Comment by murrant** [comment]
Merged at: https://github.com/librenms/laravel-vue-i18n-generator

**Pull request closed without merging**
