### PR TITLE
share() method has depreciated in Laravel 5.4

### PR DESCRIPTION
**Pull request by yateric**
Use singleton() for service binding as Laravel 5.4 depreciated share() method.

### CODE REVIEW

**Comment by martinlindhe** [comment]
@yateric Thanks for this!
Does singleton() exist in older versions than 5.4 of Laravel?

**Comment by yateric** [comment]
@martinlindhe It existed in 5.3 but removed in 5.4.

For more information, please see the "share Method Removed" section in [Laravel 5.4 upgrade guide](https://laravel.com/docs/5.4/upgrade)

**Comment by martinlindhe** [comment]
I think you misunderstood. I'm asking if the singleton() method is new to 5.4 or not (if this change will break users on laravel 5.3 or older)

**Comment by martinlindhe** [comment]
Okay, it appears the singleton()  has been around since Laravel 4.x even. Thank you very much for this!

**Comment by martinlindhe** [comment]
I released 0.1.9 that can be fetched with composer with this fix included, thanks again!

**Comment by yateric** [comment]
Just checked it appear in Laravel 4.0.  Thanks for your quick response and great tool!

**Comment by ebisbe** [comment]
"illuminate/console": "~5.1.0|~5.2.0|~5.3.0",
"illuminate/support": "~5.1.0|~5.2.0|~5.3.0" 

Have to be updated also. I don't have a fork. Can you updated it @martinlindhe ?

**Comment by martinlindhe** [comment]
@ebisbe Thanks, I'll fix that now

**Comment by martinlindhe** [comment]
Okay, version 0.1.10 has been released, with updated composer.json, @ebisbe could you verify it works for you?

**Comment by ebisbe** [comment]
@martinlindhe All packages I have installed are using share() ... 

It has been installed but I cannot confirm is 100% is working. It should be working though. I'll confirm once all is perfectly tested.

**Comment by yateric** [comment]
@martinlindhe For me, it works.

**Comment by martinlindhe** [comment]
@yateric thanks for the info!

**Pull request merged**
