### PR TITLE
Make generateMultiple and allocateLocaleArray deterministic

### PR DESCRIPTION
**Pull request by Jellyfrog**

### CODE REVIEW

**Comment by Jellyfrog** [comment]
@kapalla could you test this?

**Comment by kapalla** [comment]
@Jellyfrog it work's

Thank you!

btw: I think you can remove the import of Traversable at line 6

**Comment by Jellyfrog** [comment]
Ping @martinlindhe

**Comment by Jellyfrog** [comment]
Closing in favor of #112

**Pull request closed without merging**
