### PR TITLE
#56 Extended to generate multiple files per locale

### PR DESCRIPTION
**Pull request by rabrowne85**
I had the same requirement as @ngstwr in Issue #56 and have taken a stab at getting this working.

I've run the tests that are built in, but not sure if we need to extend these to catch the new use case. I don't see any tests pertaining to the original ```--multi``` flag so didn't have anything I could copy.

I have seen there's another pull-request waiting, so there may be some alterations if this is merged into the source.

Any comments, please let me know.

### CODE REVIEW

**Comment by martinlindhe** [comment]
Looks good and I'm thankful you introduce the new behavior as disabled by default so It should not cause issues for existing users.

I just merged that other PR so this need a rebase first.

**Comment by rabrowne85** [comment]
No problems at all. Just rebased the code for you. Looks like all the tests are good and it still works for what I need.

Let me know if there's anything else you need.

**Comment by martinlindhe** [comment]
Looks all good, thanks for your contribution!

**Comment by martinlindhe** [comment]
I just pushed out 0.1.38 which contains these changes.

**Pull request merged**
