### PR TITLE
Allow multiple umd files to load into global.vuei18nLocales

### PR DESCRIPTION
**Pull request by murrant**

### CODE REVIEW

**Comment by murrant** [comment]
Hmm, maybe not use es6 here?

**Comment by martinlindhe** [comment]
> Hmm, maybe not use es6 here?

Yes, this should not use es6.

Also, I'm not sure about the necessity of this feature. What is the use case?

**Comment by murrant** [comment]
I am loading languages selectively via external template.  So just simple: <script>fallback.js</script><script>{{ app()->getLocale() }}.js</script>

With existing code, you lose the fallback language (I have many partial translations in my app).

**Comment by murrant** [comment]
updated to not use es6, I'll update tests if it is ok.

**Comment by murrant** [comment]
@martinlindhe Anything else needed to get this merged?

**Comment by martinlindhe** [comment]
LGTM

**Pull request merged**
